### PR TITLE
Update IntervalTree.java

### PR DESCRIPTION
**Pull request by eklinger**
Expose root node to subclasses

### CODE REVIEW

**Comment by eklinger** [comment]
Would be great to expose the root node so subclasses can access it. Additionally, a filter passed to overlap() would also be useful to decide if an interval should be added to the results and also to do any processing on the node.

**Comment by pmeisen** [comment]
Hi eklinger! 

Thanks you so much for the feedback and the great feature ideas. I will have a look at the accessibility of `root` tonight and see if the change to `protected` would be somehow dangerous (not that I think so out of my head), but don't forget the actual `root` element may change after the tree is rebalanced, thus storing a pointer to the current `root` anywhere else than in the tree, is not recommended.

I also remember an email from you regarding a feature request to sort the returned nodes by their duration. I will also have a look at this one and the `filter` and come back to you later tonight.

Once again thank you for the feedback!
Philipp

**Comment by eklinger** [comment]
Hi Philipp,
Thank you so much for taking a look! The real purpose of exposing root was
so that I could override compare() and add another filter interface like
find() takes. I have a need to either process data in an IdInterval
(extract some unique data) but don't need the resulting interval itself,
and in other cases I want to decide if an interval should be in the result
list based on a filter. I figured the tree traversal would be a great place
to do it since it's already O(log n) rather than doing it after getting the
overlap intervals and doing another O(n) operation.

Thank you
Evan

**Comment by pmeisen** [comment]
Hi Evan,

I may misunderstand your problem, but the library may have already something like that in place. Can you show/explain more detailed what you are trying to filter the values by? Maybe a simple example would be great, so that I can lead you in the right direction on how to solve it with the library, or which features we actually would add to help you out.

**Comment by eklinger** [comment]
I am using an IDInterval with a custom 'id' object. These objects have some
set of tags associated with them. In some cases I only need to extract the
unique set of tags across all of my interval objects and don't care for the
interval itself (e.g. I would not use the result list from overlap()). In
another case I only want the intervals matching a certain condition on my
'id' object:

This is what I had in mind:

 protected void _overlap(IntervalTreeNode node, IInterval query,
Collection<IInterval> result, NodeFilter filter) {

        if (node == null) {
            return;
        }

        ...
            node.getIntervals().forEach(interval -> {

                if (filter.shouldInclude(sessionInterval.getId())) {

                    result.add(interval);

                }
            });
        }
...
    }

Calling it like so:

tree.overlap(range, x -> x.SomeAttribute().equals("test"));
Only get the intervals where IdInterval 'id' object attribute matches 'test'

Rather than:

results = tree.overlap(range);
results.forEach(x -> x.getId().SomeAttribute().equals("test") .... )

With the filter I can also extract data as the tree visits the overlapping
intervals:

Set<String> uniqueTags;

tree.overlap(range, new NodeFilter() {

boolean shouldInclude(IInterval interval) {
uniqueTags.addAll(interval.getId().getTags());
return false;

}
}
);

In the above case I only care about the unique set of tags across my
intervals and don't need any result list returned.

I hope this makes sense.

Thanks
Evan

**Comment by pmeisen** [comment]
Why don't you just do:

        final IntervalTree tree = IntervalTreeBuilder.newBuilder()
                .usePredefinedType(IntervalType.NUMBER, false)
                .collectIntervals(interval -> new ListIntervalCollection())
                .enableWriteCollections()
                .build();

        // let's add 100 intervals from 0, 100 -> 99, 100 and a random id
        IntStream.range(0, 100).forEach(i ->
                tree.insert(new IdInterval<>(UUID.randomUUID(), i, 100)));

        // now let's find all the once overlapping 100, 100 (which are all), and 
        //   have an `id` (or whatever attribute) that starts with "1"
        final List<IdInterval<UUID, Integer>> res = tree.overlap(new IntegerInterval(100, 100)).stream()
                .map(interval -> (IdInterval<UUID, Integer>) interval)
                .filter(res -> res.getId().toString().startsWith("1"))
                .collect(Collectors.toList());

        // output
        System.out.println(res);

There is no way that your filtering would increase the performance of the overlap operation, so you will use the feature of the `tree`. The filtering is applied to whatever the `tree` streams out. I cannot think of any scenario in which the knowledge about a filter, would have impact on the `IntervalTree`'s actual job (finding overlapping, etc. intervals). Hope I understood your question correctly.

**Comment by eklinger** [comment]
I can do that but now I’m bound by O(n) rather than log n, right?

**Comment by pmeisen** [comment]
No you are not, the tree is still utilizing it's capacity to select the values in `O(log n)`. Let's say you have 10,000 intervals in your tree. And select some via overlap (which is performed in  `O(log n)`). The resulting set of intervals (let's say k intervals) is now filtered in linear time (`O(k)`). If you want to increase selection of intervals by an attribute you should use another index-structure that suites the filter you apply to the intervals. 

**Starting to fantasize...**
Something that would be interesting at this point, would be if you would have to indexes over the same data, one that performs your "filter" and the other that performs the "overlap" and then intersect these two (`BitMaps` are good for that: https://github.com/RoaringBitmap/RoaringBitmap) :).

**Comment by pmeisen** [comment]
1. So let me summarize this a little, I think that the `sort` and the `filter` are operations that should be applied  **after** the `intervals` are retrieved from the `tree`. Because doing it anywhere else, would have no benefit regarding the performance (the `IntervalTree` is a structure designed to increase performance for the `overlap` (and some other interval-based) operations).

--> please utilize the `filter` and `sort` capacities from the `Collection` returned by the interval-operations, i.e., `tree.overlap(...).filter(...).collect(...)` or `tree.overlap(...).sort(...).collect(...)`

2. Accessibility of the `root` element. I don't see any problem with doing that (just that the person utilizing the `root` element must be aware, that the `root` may change. 

--> Would it be ok here, if we implement a `getRoot()` with `protected` access instead. In that case it is more obvious that you should call `getRoot()` and not store the result - and I would add some JavaDoc explanation.

3. What I get from this discussion. Currently the results are pushed into a `List`, which is returned by the operation. It may be a good idea to return a stream, in that case, the filter would be applied directly when the intervals are pushed through, maybe this is what you mean :)?!

Instead of
```
final List<IInterval> result = new ArrayList<>();
_overlap(this.root, query, result);
return result;
```

better something like
```
final Stream<IInterval> result = ...
_overlap(this.root, query, stream);
return stream;
```

I would have to read up on streams myself, since I normally just utilize and not implement them, but it cannot be to hard :) (https://stackoverflow.com/questions/30685623/how-to-implement-a-java-stream)

**Comment by eklinger** [comment]
True, it'd be O(k) I was just thinking that my k could still be large and
thought utilizing the overlap method during tree traversal would eliminate
that concern.

**Comment by pmeisen** [comment]
Yeah I get it, I think the streaming (see previous comment `3.`) would help in that case, so that the k-items are not actually first added to a `List` (which is then filtered or sorted) and instead piped through a stream.

**Comment by eklinger** [comment]
That makes sense. I am in agreement with all your other points.

Thanks again
Evan

**Comment by pmeisen** [comment]
`Streaming` via `overlapStream()` and `getRoot()` is available in `1.6.3`

https://github.com/Breinify/brein-time-utilities/releases/tag/1.6.3

**Pull request closed without merging**
